#!/bin/bash
#$ -pe openmpi 64
#$ -l h_rt=0:01:00
#$ -N TEST-4-8
#$ -cwd

APP=./parsort
ARGS="4"

# Get OpenMPI settings
. /etc/bashrc
module load openmpi/gcc

# Make new hostfile specifying the cores per node wanted
ncores=1
HOSTFILE=$TMPDIR/hosts
for host in `uniq $TMPDIR/machines`; do
    echo $host slots=$ncores
done > $HOSTFILE
nhosts=`wc -l < $HOSTFILE`
totcores=`expr $nhosts \* $ncores`

# Use regular ssh-based startup instead of OpenMPI/SGE native one
unset PE_HOSTFILE
PATH=/usr/bin:$PATH

$MPI_RUN -np $totcores --hostfile $HOSTFILE $APP $ARGS